version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    volumes:
      - leaderboard:/app/fe/json
    command: ["yarn", "start"]
    ports:
      - "3000:3000"

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - leaderboard:/app/backend/json
    command: ["yarn", "start"]

volumes:
  leaderboard:
    external: true
