version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: fe.Dockerfile
    volumes:
      - leaderboard:/app/fe/json
    command: ["yarn", "start"]
    ports:
      - "3000:3000"
  job:
    build:
      context: .
      dockerfile: job.Dockerfile
    volumes:
      - leaderboard:/app/jobs/json

    command: ["yarn", "start"]

volumes:
  leaderboard:
    external: true
